# setup

["docs:setup"]
depends = ["docs:setup:*"]

["docs:setup:yarn"]
dir = "{{config_root}}/docs"
run = "yarn install"
sources = ["yarn.lock", "package.json"]
outputs = { auto = true }

# check

["docs:check"]
depends = ["docs:check:*"]

["docs:check:links"]
depends = ["docs:setup"]
dir = "{{config_root}}/docs"
run = '''
lychee \
  --verbose \
  --no-progress \
  --exclude '(github)\.com' \
  --include-fragments \
  --max-concurrency 10 \
  --max-retries 0 \
  --exclude-path python \
  './**/*.mdx'
'''
sources = ["**/*.mdx"]
outputs = { auto = true }

["docs:check:snippets"]
depends = ["docs:setup"]
dir = "{{config_root}}/docs"
run = "yarn exec embedme --source-root=.. ./**/*.mdx --verify --silent"
sources = ["**/*.mdx", "../python/examples/**/*", "../typescript/examples/**/*"]
outputs = { auto = true }

# fix

["docs:fix"]
depends = ["docs:fix:*"]

["docs:fix:snippets"]
depends = ["docs:setup"]
dir = "{{config_root}}/docs"
run = "yarn exec embedme --source-root=.. ./**/*.mdx --silent"
sources = ["**/*.mdx", "../python/examples/**/*", "../typescript/examples/**/*"]
outputs = { auto = true }

# run

["docs:run"]
depends = ["docs:build"]
dir = "{{config_root}}/docs"
run = "mintlify dev --port 3333"
