name: Auto Label PRs

on:
  - pull_request_target

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    if: github.repository == 'i-am-bee/beeai-framework'
    steps:
    - uses: actions/labeler@v5
      with:
        sync-labels: true