name: Documentation

permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      # TODO: to be updated
      - 'docs-mintlify/**/*.mdx'
  pull_request:
    paths:
      - 'docs-mintlify/**/*.mdx'
      - 'python/**/*.py'
      - 'typescript/**/*.ts'

jobs:
  links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fail: true
          # Only check docs
          args: |
            --verbose
            --no-progress
            --exclude '(github)\.com'
            --include-fragments
            --exclude-path=./docs-mintlify/python
            --exclude-path=./docs-mintlify/typescript
            --max-concurrency 10
            --max-retries 0
            './**/*.mdx'

  snippets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Enable Corepack
        run: corepack enable
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          # TODO: to be updated
          node-version-file: "docs-mintlify/.nvmrc"
          cache: "yarn"
          # TODO: to be updated
          cache-dependency-path: "docs-mintlify/yarn.lock"
      - name: Install dependencies
        run: yarn install --immutable
      - name: Check snippets
        run: yarn snippets:check