name: Documentation

permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    paths:
      - 'docs/**/*.mdx'
      - 'python/**/*.py'
      - 'typescript/**/*.ts'

jobs:
  snippets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: mise docs:check
