name: Build documentation

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Copy root
        run: cp *.md docs-deprecated/

      - name: Copy TypeScript Documentation
        run: |
          cp -r ./typescript/docs docs-deprecated/typescript
          cp ./typescript/*.md docs-deprecated/typescript
          cp ./typescript/examples/README.md docs-deprecated/typescript/examples.md

      - name: Copy Python Documentation
        run: |
          cp -r ./python/docs docs-deprecated/python
          cp ./python/*.md docs-deprecated/python
          cp ./python/examples/README.md docs-deprecated/python/examples.md

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v2
        with:
          fail: true
          # Only check docs
          args: |
            --verbose
            --no-progress
            --include-fragments
            --exclude-path docs-deprecated/typescript/CHANGELOG.md
            './docs-deprecated/**/*.md'
            './docs-deprecated/**/*.html'

      - name: Upload Documentation Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    if: github.event_name != 'pull_request'

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
